# Generated by Django 3.1.7 on 2021-04-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(blank=True, choices=[{'Bike', 'B'}, {'Car', 'C'}], max_length=4)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_owner', models.CharField(max_length=100)),
                ('vehicle_problems', models.CharField(max_length=100)),
                ('vehicle_reg_number', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('service_type', models.CharField(blank=True, choices=[{'P', 'Platinum'}, {'G', 'Gold'}], max_length=8)),
                ('submission_date', models.DateTimeField()),
                ('year_old', models.IntegerField(null=True)),
                ('servicing', models.ManyToManyField(blank=True, to='services.Service')),
            ],
        ),
    ]
