# Generated by Django 3.1.7 on 2021-04-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210405_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_provider',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
