# Generated by Django 3.1.7 on 2021-03-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Customer_ID', models.CharField(max_length=100)),
                ('Customer_Contact', models.CharField(max_length=30)),
                ('Customer_License', models.CharField(max_length=100)),
                ('Customer_Mail', models.CharField(max_length=100)),
            ],
        ),
    ]
