# Generated by Django 3.1.7 on 2021-04-05 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210405_2338'),
        ('eStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', to_field='username'),
            preserve_default=False,
        ),
    ]
